// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// POSTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const FILTER_POSTS = 'FILTER_POSTS';
export const CLEAR__POSTS_FILTER = 'CLEAR_POSTS_FILTER';
export const POST_ERROR = 'POST_ERROR';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';


// COMMENTS
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENT = 'GET_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const FILTER_COMMENTS = 'FILTER_COMMENTS';
export const CLEAR__COMMENTS_FILTER = 'CLEAR_COMMENTS_FILTER';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const SET_CURRENT_COMMENT = 'SET_CURRENT_COMMENT';
export const CLEAR_CURRENT_COMMENT = 'CLEAR_CURRENT_COMMENT';
